<?php
$dictionary['Audit_Events'] = array(
	'table'              => 'audit_events',
	'audited'            => false,
	'activity_enabled'   => false,
	'duplicate_merge'    => false,
	'fields'             => array(
		'id'           => array(
			'name'       => 'id',
			'type'       => 'id',
			'required'   => true,
			'vname'      => 'LBL_ID',
			'reportable' => false,
		),
		'type'         => array(
			'name'     => 'type',
			'type'     => 'char',
			'len'      => 10,
			'required' => true,
			'vname'    => 'LBL_TYPE',
		),
		'parent_id'    => array(
			'name'     => 'parent_id',
			'type'     => 'id',
			'required' => true,
			'vname'    => 'LBL_PARENT_ID',
		),
		'module_name'  => array(
			'name'     => 'module_name',
			'type'     => 'varchar',
			'len'      => 100,
			'vname'    => 'LBL_MODULE_NAME',
			'required' => true,
		),
		'source'       => array(
			'name'     => 'source',
			'type'     => 'json',
			'dbType'   => 'text',
			'vname'    => 'LBL_SOURCE',
			'required' => false,
		),
		'data'         => array(
			'name'     => 'data',
			'type'     => 'json',
			'dbType'   => 'text',
			'vname'    => 'LBL_DATA',
			'required' => false,
		),
		'date_created' => array(
			'name'       => 'date_created',
			'type'       => 'datetime',
			'vname'      => 'LBL_DATE_CREATED',
			'reportable' => false,
			'required'   => true,
		),
		'deleted'      => array(
			'name'       => 'deleted',
			'vname'      => 'LBL_DELETED',
			'type'       => 'bool',
			'required'   => true,
			'default'    => '0',
			'reportable' => false,
		),
	),
	'indices'            => array(),
	'relationships'      => array(),
	'optimistic_locking' => false,
	'unified_search'     => false,
	'full_text_search'   => false,
);
